### ISSUE TITLE
Databinding required

### ISSUE THREAD

**Issue by jhonatansabadi** [NickM-27/LinkPreview#30]
I dont use data binding on my project, but i was incapable to use the lib without adding data binding.

**Comment by NickM-27** [comment]
Thanks, can you please paste here what the error is that you get when data binding is not included in your project?

**Comment by Muragul** [comment]
Had similar issue. 
android.view.InflateException: Error inflating class com.nick.mowen.linkpreview.view.LinkPreview
Caused by: java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                                    	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
                                                                                                    	at android.view.LayoutInflater.createView(LayoutInflater.java:854)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
                                                                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
                                                                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
                                                                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
                                                                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
                                                                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
                                                                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:534)

Solved simply by enabling dataBinding
